config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end
  root to: 'home#top'
  resources :posts
  get '/help', to: 'home#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :set_less_latlng

  validates :name, presence: true, length: { maximum: 30 }
  validates :latitude, presence: true
  validates :longitude, presence: true

  belongs_to :user
  
  scope :recent, -> { order(created_at: :desc) }
  
  private
    def set_less_latlng
      self.latitude = '34.695453' if latitude.blank?
      self.longitude = '135.196289' if longitude.blank?
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :posts
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  skip_before_action :login_required, only: [:new]

  def index
    @users = User.all.order(id: :desc)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#@user.name」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
    end

    def require_admin
      redirect_to root_url unless current_user.admin?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private
    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def login_required
      redirect_to login_url unless current_user
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :login_required
  def top
  end

  def help
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = current_user.posts.order(created_at: :desc)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def update
    @post.update!(post_params)
    redirect_to posts_url, notice: "投稿「#{@post.name}」を更新しました。"
  end

  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    if @post.save
      redirect_to @post, notice: "投稿「#{@post.name}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @post.destroy
  end

  private
    def post_params
      params.require(:post).permit(:name, :description, :latitude, :longitude)
    end

    def set_post
      @post = current_user.posts.find(params[:id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private
    def session_params
      params.require(:session).permit(:email, :password)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザーの編集

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 ユーザーリスト

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_at)
      th= User.human_attribute_name(:updated_at)
      th
  tbody
    - @users.each do |user|
      tr
        td= link_to user.name, [:admin, user]
        td= user.email
        td= user.admin? ? 'あり' : 'なし'
        td= user.created_at
        td= user.updated_at
        td
          = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

app/views/admin/users/new.html.slim
h1 ユーザー登録


.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1 ユーザーの詳細

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'
= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか?" }, class: 'btn btn-danger'

app/views/home/help.html.slim
h1 ヘルプ

br
.container
  br
  h3  アカウントの管理
  ul
    li  メールアドレス・パスワードの変更
    li  アカウントの削除

  br
  h3  サービスについて
  ul
    li  投稿の非公開設定
    li  お問い合わせ

app/views/home/top.html.slim
h1 Mapost

br


.container.content
  h3  とりあえずの仕様
  ul
    li  名前の由来: 「Map + Post」
    li  地図と投稿を紐付けるアプリ
    li  地図はLeafletを使用。GoogleAPIは今回は使わない。
    li  モデルの属性を自由に決定できればアプリとしての自由度が高くなる。
  h3  やりたいこと＆追加予定機能
  ul
    li  地図にピン立てする時にフォームを表示して属性入力したい。
    li  Ajaxを利用して、ページ切り替えを最小限にしたい。
    li  CSVでインポート&エクスポートできるようにしたい。
    li  画像のアップロード&ダウンロードができるようにしたい。(ActiveStrage?)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Mapost
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light.nav-header
      .navbar-brand = link_to "Mapost", root_path

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to current_user.name, help_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'ユーザーリスト', admin_users_path, class: 'nav-link'
          li.nav-item= link_to '投稿一覧', posts_url, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link', data: { confirm: "ログアウトします。よろしいですか？" }
        - else
          li.nav-item= link_to '新規登録', '#', class: 'nav-link'
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'

    .container
      br
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      br
      = yield

app/views/posts/_form.html.slim
- if post.errors.present?
  ul#error_explanation
    - post.errors.full_messages.each do |message|
      li= message

= form_with model: post, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'post_name'
  .form-group
    = f.label :description
    = f.text_area :description, row: 5, class: 'form-control', id: 'post_description'
  .form-group
    = f.label :latitude
    = f.text_field :latitude, class: 'form-control', id: 'post_latitude'
  .form-group
    = f.label :longitude
    = f.text_field :longitude, class: 'form-control', id: 'post_longitude'

  
  = f.submit nil, class: 'btn btn-primary'

app/views/posts/_map.html.slim
.container
  br
  #map(style="height: 400px;")
  br

javascript:
  var lat = #{@post.latitude};
  var lng = #{@post.longitude};

  L.Icon.Default.imagePath = 'https://unpkg.com/leaflet@1.3.1/dist/images/';
  var map = L.map('map').setView([lat, lng], 15);
  var osmUrl = "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
  var osmAttrib = "Map data ©︎ OpenStreetMap contributors";
  L.tileLayer(osmUrl, {
    attribution: osmAttrib,
    maxZoom: 20,
  }).addTo(map);

  var marker = L.marker([lat, lng], {icon: L.spriteIcon()}).addTo(map);
  map.on("click", function(e) {
    marker.bindPopup("<b>#{@post.name}</b><br>#{@post.description}").openPopup();
  });

app/views/posts/_mapicon.html.slim
.container
  br
  #map(style="height: 400px;")
  br

javascript:
  var lat = #{@post.latitude};
  var lng = #{@post.longitude};

  L.Icon.Default.imagePath = "https://unpkg.com/leaflet@1.3.1/dist/images/";
  var map = L.map('map').setView([lat, lng], 10);
  var osmUrl = "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
  var osmAttrib = "Map data ©︎ OpenStreetMap contributors";
  L.tileLayer(osmUrl, {
    attribution: osmAttrib,
    maxZoom: 20,
  }).addTo(map);

  var marker = L.marker([lat, lng], {icon: L.spriteIcon('red')}).addTo(map);
  map.on("click", function(e) {
    marker.setLatLng(e.latlng);
    $('#post_latitude').val(e.latlng.lat);
    $('#post_longitude').val(e.latlng.lng);
  });

app/views/posts/destroy.js.erb
document.querySelector("#post-<%= @post.id %>").style.display = 'none';

var message = document.createElement('p');
message.innerText = '投稿「<%= @post.name %>」を削除しました。残りの投稿は<%= current_user.posts.count %>件です。';
document.querySelector('table').insertAdjacentElement('beforebegin', message);

app/views/posts/edit.html.slim
h1 投稿の編集

.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'

= render partial: 'form', locals: { post: @post }

= render partial: 'mapicon', locals: { post: @post }

app/views/posts/index.html.slim
h1 投稿一覧

= link_to '新規登録', new_post_path, class: 'btn btn-primary'
p
- if @posts.empty?
  .alert.alert-warning
    p 投稿がありません。
    p 新規登録から新しい投稿を追加してください。
- else
  .container
    #map(style="height: 400px;")
    br
  .mb-3
  table.table.table-hover
    thead.thead-default
      tr
        th= Post.human_attribute_name(:name)
        th= Post.human_attribute_name(:created_at)
        th
    tbody
      - @posts.each do |post|
        tr id="post-#{post.id}"
          td= link_to post.name, post
          td= post.created_at
          td
            = link_to '編集', edit_post_path(post), class: 'btn btn-primary mr-3'
            = link_to '削除', post, method: :delete, remote: true, data: { confirm: "投稿「#post.name」を削除します。よろしいですか？" }, class: 'btn btn-danger delete'
    #mapposts data-mapposts-id="<%= @posts.to_json %>"


javascript:
  L.Icon.Default.imagePath = "https://unpkg.com/leaflet@1.3.1/dist/images/";
  var map = L.map('map').setView([34.695453, 135.196289], 15);
  var osmUrl = "http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";
  var osmAttrib = "Map data OpenStreetMap contributors";
  L.tileLayer(osmUrl, {
    attribution: osmAttrib,
    maxZoom: 20,
  }).addTo(map);

  $.ajax({
    type: "GET",
    url: "/posts.json",
    dataType: "json",
    success: function(posts) {
      for(var i = 0; i < posts.length; i++) {
        var p = posts[i];
        var marker = L.marker([p.latitude, p.longitude]).addTo(map);
        marker.bindPopup(p.name)
      }
    }
  });

app/views/posts/new.html.slim
h1 投稿の新規登録

.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'

= render partial: 'form', locals: { post: @post }

= render partial: 'mapicon', locals: { post: @post }

app/views/posts/show.html.slim
h1 投稿の詳細

.nav.justify-content-end
  = link_to '一覧', posts_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Post.human_attribute_name(:id)
      td= @post.id
    tr
      th= Post.human_attribute_name(:name)
      td= @post.name
    tr
      th= Post.human_attribute_name(:description)
      td= simple_format(h(@post.description), {}, santize: false, wrapper_tag: "div")
    tr
      th= Post.human_attribute_name(:created_at)
      td= @post.created_at
    tr
      th= Post.human_attribute_name(:updated_at)
      td= @post.updated_at
    tr
      th= Post.human_attribute_name(:latitude)
      td= @post.latitude
    tr
      th= Post.human_attribute_name(:longitude)
      td= @post.longitude

= render partial: 'map', locals: { post: @post }

= link_to '編集', edit_post_path, class: 'btn btn-primary mr-3'
= link_to '削除', @post, method: :delete, data: { confirm: "投稿「#@post.name」を削除します。よろしいですか？" }, class: 'btn btn-danger'
br